[package]
name = "serde_repr"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"

[dev-dependencies]
compiletest = { package = "compiletest_rs", version = "0.3", features = ["stable"] }
serde = "1.0"
serde_json = "1.0"
